---
abstract: 'Interface to the DEAfilter RESTful API.'
author:
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  Data::Validate::Email: 0.04
  HTTP::Request::Common: 1.26
  JSON: 2.15
  LWP::UserAgent: 2.33
  Mouse: 0.93
  MouseX::Params::Validate: 0.02
  Readonly: 1.03
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Filter-DisposableEmail
provides:
  Filter::DisposableEmail:
    file: lib/Filter/DisposableEmail.pm
    version: 0.02
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
